# Generated by Django 3.1 on 2020-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest_options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_option',
            name='antiquity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
