# Generated by Django 3.1 on 2020-08-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest_options', '0002_latest_option_antiquity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_option',
            name='antiquity_id',
            field=models.IntegerField(default=0),
        ),
    ]
