# Generated by Django 3.1 on 2020-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_antiquities', '0003_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiquity',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='antiquity',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='antiquity',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
